New anim english translation
glifem/rp-translations pull request #5
Opened 2022-04-18 11:13 UTC by YRTTV

Fixing missing translation in english

2022-04-18 20:54 UTC, Stacced requested changes
Plusieurs changements sont nécessaires sur certaines traductions.

2022-04-18 20:54 UTC, Stacced commented on en.lua
> +	anim_typing_keyboard_one = "Typing Keyboard 1",
"Type on keyboard" au lieu de "Typing"

2022-04-18 20:54 UTC, Stacced commented on en.lua
> +	anim_surrend_one = "Surrend 1",
"Surrender" au lieu de "Surrend" (pour les 4 traductions)

2022-04-18 20:54 UTC, Stacced commented on en.lua
> +	anim_ready_pounce = "Ready to pounce",
"bounce", pas "pounce"

2022-04-18 20:54 UTC, Stacced commented on en.lua
> +	anim_couch_left = "Couch left hand on floor",
"Crouched, left hand on floor"

2022-04-18 20:54 UTC, Stacced commented on en.lua
> +	anim_hold_position_one = "Hold Position 1",
`P` minuscule pour les 3 traductions

2022-04-18 20:54 UTC, Stacced commented on en.lua
> +	anim_laid_counter_one = "Laid counter 1",
"Laid on bar" plutôt

2022-04-18 20:54 UTC, Stacced commented on en.lua
> +	anim_scream_out_veh = "Scream out the vehicle (to. left)",
Enlever le `.` à la fin de "to"

2022-04-18 20:54 UTC, Stacced commented on en.lua
> +	arm_on_door_veh_left = "Arm on the car door (to. left)",
Enlever les `.`

2022-04-18 20:54 UTC, Stacced commented on en.lua
> +	kicking_the_ground = "Kicking on the ground",
"Kick ground"

2022-04-18 20:54 UTC, Stacced commented on en.lua
> +	hiding_weapon_behind_back = "Hiding a weapon behind my back",
"Hide weapon behind my back"

2022-04-19 03:25 UTC, YRTTV commented
Ajouté au dernier commit

2022-04-19 08:16 UTC, Stacced approved these changes

2022-04-19 08:16 UTC, merged